name: hackathon_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  accordion: ^2.6.0
  awesome_snackbar_content: ^0.1.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Dress.JPG
    - assets/Dress2.jpg
    - assets/outfit1(back).jpg
    - assets/outfit1(front).jpg
    - assets/outfit1(pose).jpg
    - assets/outfit2(back).jpg
    - assets/outfit2(front).jpg
    - assets/outfit2(pose).jpg
    - assets/outfit2(frontt).jpg
    - assets/outfit3(back).jpg
    - assets/outfit3(front).jpg
    - assets/outfit3(pose).jpg
    - assets/outfit4(front).jpg
    - assets/outfit4(back).jpg
    - assets/outfit4(pose).jpg
    - assets/checkout.jpg
    - assets/checkout2.jpeg

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
